### PR TITLE
make RequestStream not dependent on CF log lines

### PR DESCRIPTION
**Pull request by emilymcafee**
refactor:
  - RequestStream becomes more generic: works with path & query string only (instead of CF log line)
  - add `GeneratePath(type)` stream to do a generic log --> path&querystring conversion. Currently accepts `"cloudfront"` as type.
  - add bin/generatepath
  - update bin/cflogreplay to reflect this structure

cc @yhahn

### CODE REVIEW

**Comment by yhahn** [comment]
:+1:

**Comment by yhahn** [comment]
Do you want to add a new bin for going from cfloglines => paths?

**Comment by emilymcafee** [comment]
@yhahn y, switched to bin/generatepath to do something like `generatepath cloudfront` --> idea is we can add something like `generatepath elb` for other kinds of logs.

**Comment by yhahn** [comment]
@emilymcafee add to `package.json` bin so that `npm link` knows what commands to make global? (https://github.com/mapbox/cloudfront-log-reader/blob/master/package.json#L22-L25)

And then :ship:

**Comment by emilymcafee** [comment]
:ok_hand:

**Pull request merged**
